### PR TITLE
Implement interface methods for working with checkboxes, radio button…

### PR DESCRIPTION
**Pull request by jtwatson**
Implement interface methods for working with checkboxes, radio buttons and select’s.  Implement handling for disabled fields.  Substantially expands the test cases for forms. 

Fix for #43

### CODE REVIEW

**Comment by lxt2** [comment]
Happy to merge this, but did you intend for the author email on that commit to be a different one from your profile one @jtwatson?

**Comment by jtwatson** [comment]
I rebased to fix the email address, but couldn't figure out how to update this PR.  So there is a new PR.

**Comment by jtwatson** [comment]
Okay, got it fixed.  Figured it out after reading isaacs/github#361 

Sorry about the mess.

**Comment by headzoo** [comment]
@lxt2 - As you accept and merge these pull requests, can you be sure to update the "contributors" section of the readme as well.

**Comment by lxt2** [comment]
Yup, no probs @headzoo.

**Comment by lxt2** [comment]
Many thanks @jtwatson!

**Pull request merged**
